# Server 设置
server:
  port: 8188
# Sring 配置
spring:
  devtools:
    restart:
      enabled: true
      exclude: templates/**
  thymeleaf:
    prefix:
      classpath: /templates/
    mode: LEGACYHTML5
    suffix: .html
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/traveldemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  type-aliases-package: com.zzp.travel.stage.**.domain
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  #RowBounds第一个参数offset当做页码，默认为false
  offsetAsPageNum: true
  #使用RowBounds分页会进行count查询，默认为false
  rowBoundsWithCount: true
  #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: false
  #支持通过Mapper接口参数来传递分页参数
  supportMethodsArguments: true
  #设置为true时，如果pageSize=0遍历全部结果，相当于没有分页
  pageSizeZero: true
  #映射参数
  params: count=countSql

#日志打印
logging:
  level:
    #打印SQL信息
    com.zzp.travel.stage: debug
